version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inflation_db
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_password
      POSTGRES_DB: inflation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inflation-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: inflation_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - inflation-net

volumes:
  postgres_data:

networks:
  inflation-net:
  